### PR TITLE
Small refactorings

### PR DESCRIPTION
**Pull request by bogem**
I think, it is a little bit cleaner now

### CODE REVIEW

**Comment by awishformore** [comment]
This looks fine. You could also use `gometalinter` and fix all remaining issues with that one. Otherwise I might do it, so we have everything in idiomatic in just one PR.

**Comment by bogem** [comment]
Ok, I will do it myself

**Comment by bogem** [comment]
Done!

**Comment by awishformore** [comment]
Cool, thanks a lot. I'll take a look soon and merge if it looks good.

**Comment by bogem** [comment]
Hope you'll merge it😊

**Comment by bogem** [comment]
I'm still hoping

**Comment by awishformore** [comment]
I'll check it now, thanks again.

**Comment by awishformore** [comment]
Thanks for the cleanup, a lot less errors on the linters now, everything looks solid.

**Comment by bogem** [comment]
😌

**Pull request merged**
