### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ZhengHe-MD**
~~convert tab to space in line 738~~
convert spaces to tab in all code segments to correct the alignment, for example

before: 

```go
type config struct {
	Chart struct{
        Values map[string]interface{}
    }
}
```

after:
```go
type config struct {
    Chart struct{
        Values map[string]interface{}
    }
}
```

### CODE REVIEW

**Comment by sagikazarmark** [comment]
I don't think this is right, Go code is always tab-indented.

**Comment by ZhengHe-MD** [comment]
@sagikazarmark Thanks for pointing that out, I was trying to keep consistent with the code segment, other lines use spaces. Yeah, I agree, Go code is always tab-indented. Ultimately I just wanted to make the lines aligned correctly. I can also convert all spaces in that segment to tabs instead. : )

**Comment by ZhengHe-MD** [comment]
@sagikazarmark I open the option 'show whitespaces' of my IDE, and see both spaces and tabs used. I convert all spaces in Go segments to tabs, but feel free to check that yourself.

**Comment by sagikazarmark** [comment]
Thanks @ZhengHe-MD !

**Pull request closed without merging**
