### PR TITLE
IsSet() returns false when flags are not set

### LINKED ISSUE #276: Binding with cobra flag results on IsSet always true
When I bind a key to a cobra flag, when I ask IsSet I always get true, even if the flag was not set in the command line flags as well.

Do I miss something or this is a real issue?

### LINKED ISSUE #580: IsSet always returns true if the key is bound to a flag.
It is not possible to use spf13/pflag without specifying a default value, and it is not a pointer, so you cannot set it to nil.  pflag does have a method `Changed()` which can test whether something was set with the flag, as well as unexported functions to test if the value is currently the zero value.

However, if you use viper.BindPFlag, when you call IsSet, the unexported find() method will return the value of the pflag as the very last condition, and it does not check whether it is the zero value, so it will always return true.

### PR DESCRIPTION
**Pull request by benoitmasson**
Added flexibility to `find()` function with an extra boolean argument, so that it can be used both by `Get()` (to retrieve a value, including flag's default) and `IsSet()` (whether the key is set, ignoring flag's default).

Fixes #276 
Fixes #580

(+ added some tests to enforce this behavior)

### CODE REVIEW

**Comment by benoitmasson** [comment]
Just rebased on `master`, maybe this could be merged sometime?

This solves a small, but real issue.

**Comment by sean-** [comment]
@benoitmasson Do you have an updated version of this PR that applies cleanly to `master`?

**Comment by benoitmasson** [comment]
@sean- Not sure I get your point… `IsSet` is used to tell whether a config key is defined anywhere (other than flag default, which was not the case before this PR), so comparing the value to `defaultZeroValue()` does not make sense…

`nil` is the default zero value of a `map[string]interface{}` value, which is why values are matched against it to check for existence.

However I may have misunderstood your remark, so feel free to send a test which fails and I will try to fix it.

**Comment by berniedurfee-ge** [comment]
Is this waiting on something specific?

**Comment by tsuna** [comment]
Can we get this merged please?

**Comment by hacdias** [comment]
@bep @spf13 what's the state of this PR? This would actually be really useful.

**Comment by hairyhenderson** [comment]
There's a merge conflict, but otherwise this seems ready to merge. Would be awesome to see some movement here!

**Comment by benoitmasson** [comment]
Just rebased, it all looks good.

Things have changed since my last update, but this PR is quite light and merging should not be an issue.

**Comment by sagikazarmark** [comment]
Thanks for the PR and the ping. I'll review this PR shortly.

**Comment by sagikazarmark** [comment]
Also fixes #580

**Pull request merged**
