### PR TITLE
#680 hide logger behind an interface

### PR DESCRIPTION
**Pull request by generikvault**
Hi,
As described in #680 I want to use viper with a custom logger. Viper contains currently logs to `log.Fatal`, `log.Printf`, `jww.INFO.Println`, `jww.ERROR.Println`.

Both `log` and `jww` (jwalterweatherman) allow custom output streams but using them gets a bit hacky with my system wide log format, log level and special log files for different components.

So I've hidden the actual Logger behind an interface like this:
``` go
// Logger collects log messages.
var Logger interface {
    Infof(string, ...interface{})
    Errorf(string, ...interface{})
    Fatalf(string, ...interface{})
    ...

    Info(...interface{})
    Error(...interface{})
    Fatal(...interface{})
    ...
} = logrus.New()

func DoX(){
    logger.Info("Done X")
}
```

Kind Regards

GeneriK

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Can we use the builtin log package or a simple wrapper around it instead? I'm not a huge fan of depending on external libraries in projects like this one.

**Comment by generikvault** [comment]
Good point. I wrote the local logger type in a way, that it ignores trace, debug and warning messages analog to the defaultsetting of jwalterweatherman.

**Comment by generikvault** [comment]
@sagikazarmark do you like the local logger type as implemented?

**Comment by sagikazarmark** [comment]
I think it would be better to have a separate interface defined (not inline), and instead of a single global logger, one should be able to override it per viper instance as well.

`viper.New` should probably initialize a default logger, so a global logger would essentially become unnecessary.

**Pull request closed without merging**
