### PR TITLE
Add SetKeyDelimiter

### LINKED ISSUE #170: RFE: Allow changing the Key Delimiter for accessing nested values
I am talking about this field of Viper struct:

```
// Delimiter that separates a list of keys
// used to access a nested value in one go
keyDelim string
```

This can be useful in the following circumstances:
1. The keys in the config file contain periods.
2. Config key is being generated by something that uses a different delimiter - can save an unnecessary strings.Replace().

Looking at the code, it should be a simple matter of adding a SetKeyDelim() method.

### PR DESCRIPTION
**Pull request by robertgzr**
Allow changing the Key Delimiter for accessing nested values.

Fixes #170

### CODE REVIEW

**Comment by m4agenbitter** [comment]
I would really appreciate it if someone would be so kind to merge this.

**Comment by GrantSeltzer** [comment]
This would be very useful because if I want to use configuration keys that are file names (i.e. `file.txt`) it currently breaks on any accessor method.

**Comment by GrantSeltzer** [comment]
@spf13 @bep Any chance we could bother you to take a look at this?

**Comment by Thoro** [comment]
Could we finally merge this, since it's approved and hanging here for 1.5 years?

**Comment by sagikazarmark** [comment]
Fixed in #794

**Comment by grantseltzer** [comment]
cc @indecisivedragon @jarvision :)

**Pull request closed without merging**
