### PR TITLE
Use "go install"

### PR DESCRIPTION
**Pull request by guettli**

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Are you sure this is necessary? I don't know the difference between get and install anymore.

**Comment by guettli** [comment]
I don't know all the details, but AFAIK `go install` is recommended.

See: https://go.dev/doc/go1.18#go-get

**Comment by sagikazarmark** [comment]
As far as I understand, go get should be used to install a dependency, go install is for downloading and installing executables.

**Comment by guettli** [comment]
@sagikazarmark yes, I guess you are right. Sorry for the noise.

**Pull request closed without merging**
