### PR TITLE
Fix panic in AddConfigPath

### PR DESCRIPTION
**Pull request by dAdAbird**
Passing the environment variable without any path separators to AddConfigPath (e.g. `AddConfigPath("$MY_APP_PATH")`) causes panic:

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/spf13/viper.absPathify(0xb94fc0, 0xf, 0x0, 0x0)
    /home/andrew/projects/go/src/github.com/spf13/viper/util.go:61 +0x7e1
github.com/spf13/viper.(*Viper).AddConfigPath(0xc8201320e0, 0xb94fc0, 0xf)
    /home/andrew/projects/go/src/github.com/spf13/viper/viper.go:320 +0x47
github.com/spf13/viper.AddConfigPath(0xb94fc0, 0xf)
    /home/andrew/projects/go/src/github.com/spf13/viper/viper.go:317 +0x37
```

Adding the tailing slash to path fix this (e.g. `AddConfigPath("$MY_APP_PATH/")`), but think its better to handle such cases in the lib and don't panic)

### CODE REVIEW

**Comment by absourdnoise** [comment]
About the tests failing against tip: https://groups.google.com/forum/#!topic/golang-nuts/HNd8E1XJElk
Adding the -t flag to go get should help.

**Comment by awishformore** [comment]
Actually, tip is set to allow failure on travis, I don't know why it shows on github as failed.
You could speed up the process by signing the CLA, though.

**Comment by awishformore** [comment]
It seems like your `.travis.yml` file is out-of-date. If you could rebase your branch, the build would pass.

**Comment by awishformore** [comment]
@dAdAbird are you going to rebase?

**Comment by dAdAbird** [comment]
@awishformore yes, I'm. Sorry was busy for a while.

**Comment by sagikazarmark** [comment]
This should already be fixed

**Pull request closed without merging**
