### PR TITLE
fix(leak): fix leak in dependency magiconair/properities

### PR DESCRIPTION
**Pull request by liubog2008**
https://github.com/magiconair/properties/pull/35

### CODE REVIEW

**Comment by sagikazarmark** [comment]
@liubog2008 I think you'll have to rebase your branch, probably reset and resubmit the changes.

**Comment by liubog2008** [comment]
updated @sagikazarmark

**Comment by liubog2008** [comment]
@sagikazarmark fix cla

**Comment by sagikazarmark** [comment]
Thanks @liubog2008

**Pull request merged**
