### PR TITLE
 Support `.env` format files

### PR DESCRIPTION
**Pull request by mexisme**

### CODE REVIEW

**Comment by loicgriffie** [comment]
Any chance you merge this PR ?

**Comment by bxcodec** [comment]
Any chance to merge this PR?

**Comment by mexisme** [comment]
> Any chance to merge this PR?

I don't think I have the permissions to do this.

// @spf13

**Comment by arranf** [comment]
@spf13 Any chance of getting this merged?

**Comment by batazor** [comment]
@spf13 ping :)

**Comment by bxcodec** [comment]
@spf13 

When will this released?

**Comment by sagikazarmark** [comment]
I plan to tag a release soon, but no ETA yet.

**Comment by souvikmaji** [comment]
@sagikazarmark any update on the release?

**Comment by sagikazarmark** [comment]
@souvikmaji it's been released quite some time ago.

**Pull request merged**
