### PR TITLE
Add INI support

### LINKED ISSUE #194: INI support through gcfg
I'm interested in using https://godoc.org/gopkg.in/gcfg.v1 to support INI files in viper, eventually to resolve https://github.com/s3git/s3git/issues/15 and possibly others. It reads the key-value pairs into a two-level struct: https://godoc.org/gopkg.in/gcfg.v1#ex-ReadStringInto--Subsections

Could you guide me through the steps necessary to implement that new configuration file backend for Viper? I want to make sure I implement it in a way that's acceptable.

### PR DESCRIPTION
**Pull request by techknowlogick**
Fixes  #194

### CODE REVIEW

**Comment by spf13** [comment]
I personally just really dislike the ini format. Is there a reason you need it?

**Comment by techknowlogick** [comment]
@spf13 I too am not a fan of the format either, which is exactly the reason for this PR. I am a lead on https://github.com/go-gitea/gitea/ which for historical reasons uses ini, however if this PR is accepted, then the project has a roadmap in place to switch to using another configuration format, but in a backwards compatible way.

**Comment by sagikazarmark** [comment]
Personally I'd rather see a way to extend the current set of parsers (something like drivers in the *database/sql* package)

**Comment by earlzo** [comment]
#194

**Comment by earlzo** [comment]
hey @spf13, are you gonna to merge this mr?

**Comment by techknowlogick** [comment]
@sagikazarmark I'd like to see extensions in that way too, perhaps that should is an item for 2.0.

As for now, I've resolved merge conflicts and updated tests so that INI can be understood in 1.x version of viper.

**Comment by sagikazarmark** [comment]
@techknowlogick TBH I'm not so keen on adding INI support. Actually I would be open to adding it temporarily, because right now there is no way to extend current encoders. But what then? Can we remove it in v2?

Let me think about the extendable encoder solution. If it's feasible to implement in a timely manner, would it be acceptable for you to use that new API to register your custom encoder in your own code?

**Comment by techknowlogick** [comment]
I would be completely open to that solution, as that is preferable for me (I too dislike INI, but sadly it is a format that I have to work with, and having viper be able to support INI in some fashion would allow me to migrate away from INI).

Also, I think moving between major versions allows for backwards incompatible changes, so if this gets merged now, then INI doesn't have to be in v2 (although hopefully an extendable encoder solution would be available).

**Comment by techknowlogick** [comment]
@sagikazarmark following up on this, have you discussed with other maintainers re: extending v1 with encoders?

**Comment by sagikazarmark** [comment]
@techknowlogick no, unfortunately I didn't have the chance. I started playing with an encoding abstraction, but hit the wall with a few problems unfortunately.

I don't want to block this PR, so if you find some time to rebase the branch I'll review and merge it.

**Comment by techknowlogick** [comment]
@sagikazarmark thanks for the update :) I've just merged the most recent commits to master into this PR. Please let me know if you'd like me to squash this branch.

**Comment by sagikazarmark** [comment]
@techknowlogick Please do. Also, the branch is still conflicting with master. So I would suggest rebasing instead of merging.

**Comment by techknowlogick** [comment]
Squashed & rebased. Looks like Travis is also passing too. 🎉 pleade let me know if there is anything else I can do :)

**Pull request merged**
