### PR TITLE
Issue-105 Support time.Duration in viper.Unmarshal

### PR DESCRIPTION
**Pull request by yauhen-l**
Just add DecodeHook to DecoderConfig.
Allows to unmarshal into struct with time.Duration fields:
```
package main

import (
	"bytes"
	"fmt"
	"github.com/spf13/viper"
	"time"
)

type Config struct {
	Timeout time.Duration
	String  string
}

func main() {
	var cfg Config

	viper.SetConfigType("yaml")

	var yamlExample = []byte(`
Timeout: 200ms
String: it works!
`)

	viper.ReadConfig(bytes.NewBuffer(yamlExample))
	viper.Unmarshal(&cfg)

	// {Timeout:200ms String:it works!}
	fmt.Printf("%+v\n", cfg)
}
```

### CODE REVIEW

**Comment by jyellick** [comment]
This changeset looks very much like the code used in [`UnmashalExact`](https://github.com/yauhen-l/viper/blob/aebf0fcdc54f2101d72d3704b9cea0423fe66450/viper.go#L656).

Fixing Issue #105 is something I'd certainly like to see done, but could this patch be refactored so that `Unmarshal` and `UnmarshalExact` are combined to use the same codepath?  This patch, as is, I believe will still produce errors in `UnmarshalExact`.

**Comment by awishformore** [comment]
I will try to take a look at this PR soon. In the meantime, if the suggestion by @jyellick could be implemented, thaht would be great.

**Comment by awishformore** [comment]
@yauhen-l it seems straight forward enough to add the hook to the `UnmarshalExact` as well, since it already uses a custom configuration. Could you add that?

**Comment by yauhen-l** [comment]
@awishformore, I will take a look in the evening

**Comment by yauhen-l** [comment]
@awishformore, @jyellick please review

**Pull request merged**
