### PR TITLE
add support for hcl

### PR DESCRIPTION
**Pull request by patdhlk**
supporting the hashicorp configuration language HCL in viper would be great... so here it is. The design of viper made it really easy, i just love it. Great work guys

### CODE REVIEW

**Comment by patdhlk** [comment]
i forgot to update some tests...will fix it later

**Comment by spf13** [comment]
Let us know when you feel it's ready. It looks good so far. I'd love for it to be added to the readme as well.

**Comment by patdhlk** [comment]
@spf13 nice to here. I will also add it to the readme file - but i am really busy today, maybe there is some free time in the evening :smile:

**Comment by patdhlk** [comment]
@spf13 what do you think...do i have to add or change something?

**Comment by spf13** [comment]
I think it's good. I'll dig in a bit deeper in the next day or so.

**Comment by patdhlk** [comment]
ok thanks

**Comment by spf13** [comment]
Thanks for this! Merged as 79971f1

**Pull request closed without merging**
