### PR TITLE
Lookup environment variables instead of checking if the value is empty

### LINKED ISSUE #317: Allow EmptyStrings to read from Environmental Variables
The code below inside the find(key string) function in viper.go, makes it so that if an env var is set to "", the default value is used instead. I have a use case where I need the default to be overridden with empty string from the environment. Any chance this will get implemented in this way?

 envkey, exists := v.env[key]
  if exists {
    jww.TRACE.Println(key, "registered as env var", envkey)
    if val = v.getEnv(envkey); val != "" {
      jww.TRACE.Println(envkey, "found in environment with val:", val)
      return val

### PR DESCRIPTION
**Pull request by sagikazarmark**
Empty environment variables are perfectly valid values.
Fortunately Go provides a way to check whether an env var
is empty or not set.

Fixes #317 

Resubmitted #429

### CODE REVIEW

**Comment by sagikazarmark** [comment]
@tsl0922 test cases provided in this PR

**Comment by dcormier** [comment]
Sure would be nice to see this working. I'd like to be able to use empty environment variables.

**Comment by sagikazarmark** [comment]
Can someone restart the build please? Tests passed for me locally.

**Comment by tsl0922** [comment]
@sagikazarmark you can do a force push to trigger it.

**Comment by sagikazarmark** [comment]
Ping Looks like tests are passing.

**Comment by sagikazarmark** [comment]
Any news?

**Comment by sagikazarmark** [comment]
Ping

**Comment by b1v1r** [comment]
Any ETA on this being merged (or rejected)? Looks like @tsl0922 reviewed this as #429, but then it stalled when it was resubmitted.

**Comment by sagikazarmark** [comment]
@bep @andrewstuart can you help us out here?

**Comment by bep** [comment]
>So my main concern here is that this has the potential to be considered a breaking change if are using empty environment variables in place of unsetting.

On one side, I think the map lookups follow the `v, ok :=` pattern, which would be similar, but I agree -- we cannot change this as the default behavior. That this is OS env vars, something "invisible", will create some very subtle bugs around. But an option (default off) would be good.

**Comment by sagikazarmark** [comment]
@andrewstuart @bep Thanks for your comments.

I added an `AllowEmptyEnv` method with tests and some documentation in the readme. By default this feature is turned off.

**Comment by sagikazarmark** [comment]
Breaking tests seem to be unrelated

**Pull request merged**
