### PR TITLE
Make the remote features optional

### PR DESCRIPTION
**Pull request by bep**
@spf13 this is a little bit quick and dirty from me -- I will clean up and make sure it works (I do not see why it shouldn't) when we agree that this is a good idea.

### CODE REVIEW

**Comment by spf13** [comment]
It looks solid to me, but I'd love to get others input on it.

**Comment by spf13** [comment]
@bketelsen Do you see anything wrong with this approach?

**Comment by bketelsen** [comment]
will look this evening.

**Comment by bep** [comment]
For reference (and some alt solutions), see https://groups.google.com/forum/#!topic/golang-nuts/IG7Pref7kkk

The motivation is clear enough in this case. 90%+ reads config from files. And this change shaves 1,4MB off the Hugo binary.

**Comment by bketelsen** [comment]
LGTM - just means I need to change my uses of this.

**Comment by bep** [comment]
Good. You should get a pretty clear and instructive error message if you try to use the remote features without the necessary import.

Will wrap this up tomorrow.

**Comment by leolara** [comment]
:+1:

**Comment by bep** [comment]
I tested it OK with etcd. Merged in be5ff3e

**Pull request closed without merging**
