### PR TITLE
Copy and insensitivise maps in Set

### LINKED ISSUE #261: Set(map) does not lowercase nested keys
Maybe it should, but it would probably be bad to modify the original map.

### PR DESCRIPTION
**Pull request by bep**
Fixes #261

### CODE REVIEW

**Comment by benoitmasson** [comment]
Sounds great indeed, I totally forgot about this case!

Just 2 minor remarks:

* don't forget to call it in `SetDefault()`, too. An maybe also in the function which updates the last map, `kvstore` (not sure about this one...)? The last map, `config`, is already dealt with in `unmarshallConfigReader()`.

* `cast.ToStringMap(v)` already performs a copy, so I guess the case `map[interface{}]interface{}` could simply be written as:
    ```golang
	value = insensitiviseMap(cast.ToStringMap(v))
```

Bonus remark: while looking for `insensitiviseMaps()` usages, I found that it is called in `Unmarshal()` and `UnmarshalExact()` (viper.go:727 and :764). These can probably be removed.

**Comment by bep** [comment]
>cast.ToStringMap(v) already performs a copy

I thought about that, but it only makes a "shallow copy", i.e. the top level.  Thanks for the other tips, a sign that I really don't know my Viper.

**Comment by bep** [comment]
I created https://github.com/spf13/viper/issues/266 for the `kvstore` case.

**Pull request closed without merging**
