### PR TITLE
Flag Binding Refactor

### PR DESCRIPTION
**Pull request by akutz**
This patch alters the way flags are handled to coincide with the documentation on the Viper README. The documentation indicated that flag bindings were late, when in fact they were very, very early. This patch changes flag bindings to behave as late bindings.

### CODE REVIEW

**Comment by spf13** [comment]
@akutz can you look into the failing test? Also can you sign the CLA?

https://cla-assistant.io/spf13/viper?pullRequest=123

**Comment by akutz** [comment]
Hi @spf13,

I'll take a look at the test as well as sign the CLA.

**Comment by akutz** [comment]
Hi @spf13,

Please review the change I made to ensure the broken test passes. The logic for handling flags has been altered as is explained in the comments in the `Get` method.

**Comment by spf13** [comment]
Merged as c374c6d

**Pull request closed without merging**
