### PR TITLE
Added default parameter on getters to return it in case it doesn't exist

### PR DESCRIPTION
**Pull request by rogersole**
Added getters allowing default values:

- `func GetDefaultString(key string, defaultValue string) string`
- `func GetDefaultBoolean(key string, defaultValue bool) bool`
- `func GetDefaultInt(key string, defaultValue int) int`
- `func GetDefaultInt64(key string, defaultValue int64) int64`
- `func GetDefaultFloat64(key string, defaultValue float64) float64`
- `func GetDefaultTime(key string, defaultValue time.Time) time.Time`
- `func GetDefaultDuration(key string, defaultValue time.Duration) time.Duration`
- `func GetDefaultStringSlice(key string, defaultValue []string) []string`
- `func GetDefaultStringMap(key string, defaultValue map[string]interface{}) map[string]interface{}`
- `func GetDefaultStringMapString(key string, defaultValue map[string]string) map[string]string`
- `func GetDefaultStringMapStringSlice(key string, defaultValue map[string][]string) map[string][]string`

### CODE REVIEW

**Comment by bep** [comment]
You know you there is an ´viper.SetDefaultValue`?

**Comment by rogersole** [comment]
Hi @bep, yes I know, but sometimes you don't want to define all the `SetDefaultValue` variables in a different code line. Just adding the option to have it in a oneliner.

**Comment by bep** [comment]
Other may chime in, but this doesn't seem to be worth it to me. If Go had a good way of adding optional arguments (other than varags), maybe ...

**Comment by awishformore** [comment]
I don't think it's necessary, seems like code bloat to me.

**Comment by taybin** [comment]
I'd like to see Sub() have a default value of an empty map[].

**Comment by awishformore** [comment]
I will close this unless someone chimes in with a real use case for this. Feel free to keep commenting.

**Pull request closed without merging**
